language: go

sudo: false

matrix:
  include:
    - go: 1.x
      env: RELEASE=true
    - go: master
  allow_failures:
    - go: master

after_success:
  - go build -ldflags="-s -w"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: AbJbEnUdLwKVc5PTcg6zN/zpYwZ+oqv27wX4SmtV7h5+04FIgPgVYnBinQbSSuwmJO9DuAIWm2ayMJ5e/fphvuY9il1Pc0kN03CrkyQK63exkf+p9lqT+/gOLG29c8F6dbX7Bf3LxtqAcjf8S+u4Xx49vTKilSw13ugQSJ5UnaAjMp/mUHxMU6klV5Xr4LQ9owB/CSTAIr2OycmSXzwDLxMjWBg8awIrxjViIudvB2wAi2LGFou17FCyPKdPD5/GPUGXu3P7tcMnfrxzAeT9LdO3ad6gBunNwHgHb+324sfK9Bsq6dGqCLMoKkRM9CLMnvre1elxAv9H9kG1S/F9eJznTuMvqliBPgnizTHw3YXA1/w9VAEbZGnNZmalAOM8a/JcmXjMQeXf5JsBNqcYOxlxqRezvsFxHw6RkdzzdM3NYKRPkpxDHsppDJVSnwRbCsIVg9HOPCbvvLKYHpgyNjHtIUoKR1rax9fPis7P+57TC63/U8KAwoO/hIJwxCWBSle4oVqvuS6SqspF87jhdRyKJfn+pKNRDGmSYIyjsQRqHjRZGyrI4znP9uZtwzxqLz8Unx21EvyITNNezosifeJqOz+yT9NExvz0wLlhF9CvYLLUBxJRi4yVVQR6DbJr0OgyEUGMjUAuiUEUSAAZ7dj5MkDI9P6G9ry69SsJDa4=
  file: simple-cgi-server
  on:
    tags: true
    repo: mback2k/simple-cgi-server
    condition: $RELEASE = true
